name: Test and Build

on: [push]

jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test

  build:
    needs: test
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        targets:
          - bundler
          - nodejs
          - web
    if: github.ref == 'refs/heads/main'
    steps: 
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - run: (cd wasm_lib && wasm-pack build --release --target ${{ matrix.ruby }}) 
      - run: rm -rf wasm_lib/pkg/.gitignore
      - run: |
          cd wasm_lib/pkg
          tmp=$(mktemp)
          jq '.name = "dice_distribution"' package.json > "$tmp" && mv "$tmp" package.json
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build_${{ matrix.ruby }}
          FOLDER: wasm_lib/pkg
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}